# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  twilio_sid: <%= ENV["TWILIO_ACCOUNT_SID"]  %>
  twilio_token: <%= ENV["TWILIO_AUTH_TOKEN"]  %>
  twilio_token: <%= ENV["TWILIO_NUMBER"]  %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: f54c7061dac417c1727a3ccdb4b84417e8ed8f82a1d0b7aa3d06153600d08ec67e0e9d8dbe6393b56180e089a19fad3f75e647ebb0513d3dd5ee58fb19a1bb66

test:
  twilio_sid: <%= ENV["TWILIO_ACCOUNT_SID"]  %>
  twilio_token: <%= ENV["TWILIO_AUTH_TOKEN"]  %>
  twilio_token: <%= ENV["TWILIO_NUMBER"]  %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: 56e60d02ff0043844843a1efabbf625f283613195ebc207ef269a6822e785aecb6473e4e7354285f6e13186ceb50c38534c14302aff146de8763c344b819e828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  twilio_sid: <%= ENV["TWILIO_ACCOUNT_SID"]  %>
  twilio_token: <%= ENV["TWILIO_AUTH_TOKEN"]  %>
  twilio_token: <%= ENV["TWILIO_NUMBER"]  %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
